param(
    [string]$Model = "ollama/qwen3:14b",
    [string]$OllamaModel = "qwen3:14b",
    [switch]$SkipClaudeCode,
    [switch]$SkipOllama
)

Write-Host "===== Free Claude Code (Ollama) 一键安装脚本 =====" -ForegroundColor Cyan
Write-Host ""

# 1. 安装 Ollama
if (-not $SkipOllama) {
    Write-Host "[1/6] 检查/安装 Ollama..." -ForegroundColor Yellow
    try {
        $ov = ollama --version 2>$null
        Write-Host "  Ollama 已安装: $ov" -ForegroundColor Green
    } catch {
        Write-Host "  正在安装 Ollama..." -ForegroundColor Yellow
        irm https://ollama.com/install.ps1 | iex
        $env:Path = "$env:USERPROFILE\AppData\Local\Programs\Ollama;$env:Path"
    }

    # 拉取模型
    try {
        $installed = ollama list 2>$null
        if ($installed -match [regex]::Escape($OllamaModel)) {
            Write-Host "  模型 $OllamaModel 已存在" -ForegroundColor Green
        } else {
            Write-Host "  正在拉取模型 $OllamaModel（首次下载约 5-20 分钟）..." -ForegroundColor Yellow
            ollama pull $OllamaModel
        }
    } catch {
        Write-Host "  [警告] 无法拉取模型，请手动运行: ollama pull $OllamaModel" -ForegroundColor Red
    }
} else {
    Write-Host "[1/6] 跳过 Ollama 安装" -ForegroundColor Yellow
}

# 2. 安装 uv
Write-Host "[2/6] 检查/安装 uv..." -ForegroundColor Yellow
try {
    $uvVer = uv --version 2>$null
    Write-Host "  uv 已安装: $uvVer" -ForegroundColor Green
} catch {
    Write-Host "  正在安装 uv..." -ForegroundColor Yellow
    irm https://astral.sh/uv/install.ps1 | iex
    $env:Path = "C:\Users\$env:USERNAME\.local\bin;$env:Path"
}

# 确保 uv 在 PATH
$userPath = [Environment]::GetEnvironmentVariable("Path", "User")
if ($userPath -notlike "*C:\Users\$env:USERNAME\.local\bin*") {
    [Environment]::SetEnvironmentVariable("Path", "$userPath;C:\Users\$env:USERNAME\.local\bin", "User")
}
$env:Path = "C:\Users\$env:USERNAME\.local\bin;$env:Path"

# 3. 安装 Claude Code CLI
if (-not $SkipClaudeCode) {
    Write-Host "[3/6] 安装 Claude Code CLI..." -ForegroundColor Yellow
    npm install -g @anthropic-ai/claude-code
} else {
    Write-Host "[3/6] 跳过 Claude Code CLI 安装" -ForegroundColor Yellow
}

# 4. 确保 pip 在 PATH
Write-Host "[4/6] 检查 pip 环境变量..." -ForegroundColor Yellow
$pythonPath = (Get-Command python).Source
$scriptsDir = Join-Path (Split-Path $pythonPath -Parent) "Scripts"
if (Test-Path "$scriptsDir\pip.exe") {
    $userPath = [Environment]::GetEnvironmentVariable("Path", "User")
    if ($userPath -notlike "*$scriptsDir*") {
        [Environment]::SetEnvironmentVariable("Path", "$userPath;$scriptsDir", "User")
        Write-Host "  已将 $scriptsDir 加入 PATH" -ForegroundColor Green
    } else {
        Write-Host "  pip 已在 PATH 中" -ForegroundColor Green
    }
    $env:Path = "$scriptsDir;$env:Path"
} else {
    Write-Host "  [警告] 未找到 pip.exe，请确保 Python Scripts 目录在 PATH 中" -ForegroundColor Red
}

# 5. 安装 free-claude-code 代理
Write-Host "[5/6] 安装 free-claude-code 代理..." -ForegroundColor Yellow
uv tool install --force git+https://github.com/Alishahryar1/free-claude-code.git

# 6. 写入配置文件
Write-Host "[6/6] 写入 Ollama 配置..." -ForegroundColor Yellow
$configDir = "$env:USERPROFILE\.fcc"
if (-not (Test-Path $configDir)) {
    New-Item -ItemType Directory -Path $configDir -Force | Out-Null
}

$configContent = @"
# Managed by Free Claude Code /admin.
# Generated by install-fcc.ps1

# Providers
OLLAMA_BASE_URL=http://localhost:11434

# Model Routing
MODEL=$Model

# Runtime
ANTHROPIC_AUTH_TOKEN=freecc
ENABLE_NETWORK_PROBE_MOCK=true
ENABLE_TITLE_GENERATION_SKIP=true
ENABLE_SUGGESTION_MODE_SKIP=true
ENABLE_FILEPATH_EXTRACTION_MOCK=true

# Web Tools
ENABLE_WEB_SERVER_TOOLS=true
WEB_FETCH_ALLOWED_SCHEMES=http,https

# Diagnostics
LOG_RAW_API_PAYLOADS=false
LOG_RAW_SSE_EVENTS=false
"@

Set-Content -Path "$configDir\.env" -Value $configContent -Encoding UTF8

Write-Host ""
Write-Host "====== 安装完成 ======" -ForegroundColor Cyan
Write-Host "Ollama 模型: $OllamaModel" -ForegroundColor Green
Write-Host "Claude Code 模型映射: $Model" -ForegroundColor Green
Write-Host ""
Write-Host "使用步骤:" -ForegroundColor White
Write-Host "  1. 启动代理:    fcc-server" -ForegroundColor Yellow
Write-Host "  2. 管理界面:    http://127.0.0.1:8082/admin" -ForegroundColor Yellow
Write-Host "  3. 运行 CLI:    fcc-claude" -ForegroundColor Yellow
Write-Host ""
Write-Host "提示: 如需修改模型，编辑 $env:USERPROFILE\.fcc\.env 中的 MODEL 行" -ForegroundColor Cyan
